<a href="https://colab.research.google.com/github/fahriyegrl/NJIT_Pytorch_Assignment/blob/main/Assignment_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Note to grader:** Each question consists of parts, e.g. Q1(i), Q1(ii), etc. Each part must be first graded  on a 0-4 scale, following the standard NJIT convention (A:4, B+: 3.5, B:3, C+: 2.5, C: 2, D:1, F:0). However, any given item may be worth 4 or 8 points; if an item is worth 8 points, you need to accordingly scale the 0-4 grade.


The total score must be re-scaled to 100. That should apply to all future assignments so that Canvas assigns the same weight on all assignments.



# Assignment 1



## Preparation Steps

In [1]:
# Import all necessary python packages
import numpy as np
import torch



## <font color = 'blue'> Question 1. Basic Operations with Tensors </font>

Your task for this question is to follow the NumPy  [**tutorial**](https://jalammar.github.io/visual-numpy/?fbclid=IwAR0tSntx5mj1aHteokRKrT4G6z77M3z0Quj40AQZ9mvKlhs2RTN3xXrc6Eo) and 'mirror' each of the operations presented in the tutorial with tensors in PyTorch.

You may find useful to consult this PyTorch introductory [tutorial](https://jhui.github.io/2018/02/09/PyTorch-Basic-operations/), and as always the full PyTorch [documentation](https://pytorch.org/docs/stable/torch.html) is the ultimate resource.

*(Please insert cells below for your answers )*

In [6]:
### Operation-1: Creating Arrays

x= torch.tensor([1,2,3])
ones= torch.ones(3)
zeros= torch.zeros(3)
randoms= torch.rand(3)
print(x)
print(ones)
print(zeros)
print(randoms)

tensor([1, 2, 3])
tensor([1., 1., 1.])
tensor([0., 0., 0.])
tensor([0.0935, 0.5264, 0.6879])


In [14]:
### Operation-2: Arithmetic(Addition/ Multiplication/Subtraction/DivisionScalar Multiplication)
result1 = x+ones
print(f"x+ones= {result1}")
result2 = x*ones
print(f"x*ones= {result2}")
result3 = x-ones
print(f"x-ones= {result3}")
result4 = x/ones
print(f"x/ones= {result4}")

x+ones= tensor([2., 3., 4.])
x*ones= tensor([1., 2., 3.])
x-ones= tensor([0., 1., 2.])
x/ones= tensor([1., 2., 3.])


In [20]:
### Operation-3: Indexing/Slicing
print(f"x= {x}")
sub = x[0]
print(f"x[0]= {sub}")
sub1 = x[1]
print(f"x[1]= {sub1}")
sub2 = x[0:2]
print(f"x[0:2]= {sub2}")
sub3 = x[1:]
print(f"x[1:]= {sub3}")


x= tensor([1, 2, 3])
x[0]= 1
x[1]= 2
x[0:2]= tensor([1, 2])
x[1:]= tensor([2, 3])


In [26]:
### Operation-4: Aggregation
min = x.min()
print(f"min= {min}")
max = x.max()
print(f"max= {max}")
sum = x.sum()
print(f"sum= {sum}")
mean = x.type(torch.float32).mean()
print(f"mean= {mean}")
std= x.type(torch.float32).std()
print(f"std= {std}")

min= 1
max= 3
sum= 6
mean= 2.0
std= 1.0


In [29]:
### Operation-5: Creating Matrices
matrix= torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
print(f"matrix= {matrix}")
ones_matrix = torch.ones((3, 2))
zeros_matrix = torch.zeros((3, 2))
random_matrix = torch.rand((3, 2))
print(f"ones_matrix= {ones_matrix}")
print(f"zeros_matrix= {zeros_matrix}")
print(f"random_matrix= {random_matrix}")

matrix= tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
ones_matrix= tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])
zeros_matrix= tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])
random_matrix= tensor([[0.6434, 0.5612],
        [0.1790, 0.1797],
        [0.8759, 0.3699]])


In [34]:
### Operation-6: Matrix Arithmetic
matrix1 = torch.tensor([[1, 2], [3, 4]])
matrix2 = torch.tensor([[5, 6], [7, 8]]))
sum= matrix1+matrix2
print(f"matrix1+matrix2= {sum}")
sub= matrix1-matrix2
print(f"matrix1-matrix2= {sub}")
matrix3= torch.rand((3,2))
matrix4= torch.rand((1,2))
sum2= matrix3+matrix4
print(f"matrix3+matrix4= {sum2}")

matrix1+matrix2= tensor([[ 6,  8],
        [10, 12]])
matrix1-matrix2= tensor([[-4, -4],
        [-4, -4]])
matrix3+matrix4= tensor([[0.6649, 1.6568],
        [0.7666, 0.9552],
        [0.9681, 0.8607]])


In [46]:
### Operation-7: Dot Product
print(ones, randoms)
result= torch.dot(ones,randoms)
print(f"result= {result}")
result1 = torch.matmul(ones, randoms)
print(f"result1= {result1}")

tensor([1., 1., 1.]) tensor([0.0935, 0.5264, 0.6879])
result= 1.3077363967895508
result1= 1.3077363967895508


In [55]:
### Operation-8: Matrix Indexing
### Operation-8: Matrix Indexing
random_matrix = torch.rand((3, 2))
print(f"random_matrix: {random_matrix}")
print("***********************************")
print(f"random_matrix[0,1]: {random_matrix[0,1]}")
print("***********************************")
print(f"random_matrix[1:3]: {random_matrix[1:3]}")
print("***********************************")
print(f"random_matrix[0:2,0]: {random_matrix[0:2,0]}")

random_matrix: tensor([[0.3691, 0.6705],
        [0.1272, 0.6710],
        [0.7757, 0.3773]])
***********************************
random_matrix[0,1]: 0.6704935431480408
***********************************
random_matrix[1:3]: tensor([[0.1272, 0.6710],
        [0.7757, 0.3773]])
***********************************
random_matrix[0:2,0]: tensor([0.3691, 0.1272])


In [59]:
### Operation-9: Matrix Aggregation
max= random_matrix.max()
print(f"max= {max}")
min= random_matrix.min()
print(f"min= {min}")
sum= random_matrix.sum()
print(f"sum= {sum}")

print("***********************************")

max2= random_matrix.max(axis=0)
print(f"max2= {max2}")
max3= random_matrix.max(axis=1)
print(f"max3= {max3}")


max= 0.7756815552711487
min= 0.12722361087799072
sum= 2.9908664226531982
***********************************
max2= torch.return_types.max(
values=tensor([0.7757, 0.6710]),
indices=tensor([2, 1]))
max3= torch.return_types.max(
values=tensor([0.6705, 0.6710, 0.7757]),
indices=tensor([1, 1, 0]))


In [60]:
### Operation-10: Transposing / Reshaping
transpose= random_matrix.T
print(f"transpose= {transpose}")
print("***********************************")
reshape= random_matrix.reshape(2,3)
print(f"reshape= {reshape}")

transpose= tensor([[0.3691, 0.1272, 0.7757],
        [0.6705, 0.6710, 0.3773]])
***********************************
reshape= tensor([[0.3691, 0.6705, 0.1272],
        [0.6710, 0.7757, 0.3773]])


In [62]:
### Operation-11: More Dimentions
ones_d = torch.ones((4, 3, 2))
print(f"ones_d= {ones_d}")
zeros_d = torch.zeros((4, 3, 2))
print(f"zeros_d= {zeros_d}")
random_d = torch.rand((4, 2, 2))
print(f"random_d= {random_d}")

ones_d= tensor([[[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]]])
zeros_d= tensor([[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]])
random_d= tensor([[[0.9162, 0.5398],
         [0.7069, 0.1303]],

        [[0.0405, 0.6338],
         [0.5409, 0.4502]],

        [[0.0624, 0.9271],
         [0.1396, 0.5913]],

        [[0.4883, 0.9090],
         [0.7776, 0.9446]]])


In [64]:
### Operation-12: Formulas
predictions = torch.tensor([3.6, 0.1, 4.1, 6.8])
labels = torch.tensor([3.0, -0.7, 3.0, 8.5])
n = predictions.size(0)
mean_square_error = (1 / n) * torch.sum(torch.square(predictions - labels))
print(f"mean_square_error= {mean_square_error}")

mean_square_error= 1.2749998569488525


In [ ]:
### Data Representation: Tables and Spreadsheets

### In PyTorch, data loading from CSV files isn't done directly using PyTorch itself
### Once the data is read throth pandas or NumPy , it can be converted into a PyTorch tensor.

In [66]:
### Audio and Timeseries
### Python has libraries such as  torchaudio for audio data.
import torchaudio
audio_path = " "
#torchaudio.load(audio_path)

In [ ]:
# For grader use only

G = [0]*2


# insert grade here  (from 0 to 8)
# G[1] =

# please justify point subtraction  s

##  <font color = 'blue'> Question 2. Quadratic Regression

In the lecture we discussed a simple regression problem, where points are coming from the line $y = 2x + 1$, plus some noise.  For this question you are asked to:

(i) Generate data points coming from a quadratic function: $ y = -x^2 + 3x +10 $, plus some noise. <br>
(ii) Modify the PyTorch model from the class in order for it to learn a quadratic function of the form $y = a x^2 + bx +c$. <br>
(iii) Train your model and report what values it computes. (Sanity check: These sould be close to -1, 3, 10)




In [71]:
###  Creating random x values
n_points = 100
x = torch.linspace(-5, 5, n_points)
x

tensor([-5.0000, -4.8990, -4.7980, -4.6970, -4.5960, -4.4949, -4.3939, -4.2929,
        -4.1919, -4.0909, -3.9899, -3.8889, -3.7879, -3.6869, -3.5859, -3.4848,
        -3.3838, -3.2828, -3.1818, -3.0808, -2.9798, -2.8788, -2.7778, -2.6768,
        -2.5758, -2.4747, -2.3737, -2.2727, -2.1717, -2.0707, -1.9697, -1.8687,
        -1.7677, -1.6667, -1.5657, -1.4646, -1.3636, -1.2626, -1.1616, -1.0606,
        -0.9596, -0.8586, -0.7576, -0.6566, -0.5556, -0.4545, -0.3535, -0.2525,
        -0.1515, -0.0505,  0.0505,  0.1515,  0.2525,  0.3535,  0.4545,  0.5556,
         0.6566,  0.7576,  0.8586,  0.9596,  1.0606,  1.1616,  1.2626,  1.3636,
         1.4646,  1.5657,  1.6667,  1.7677,  1.8687,  1.9697,  2.0707,  2.1717,
         2.2727,  2.3737,  2.4747,  2.5758,  2.6768,  2.7778,  2.8788,  2.9798,
         3.0808,  3.1818,  3.2828,  3.3838,  3.4848,  3.5859,  3.6869,  3.7879,
         3.8889,  3.9899,  4.0909,  4.1919,  4.2929,  4.3939,  4.4949,  4.5960,
         4.6970,  4.7980,  4.8990,  5.00

In [ ]:
# for grader use only

# insert grade here
# part (i): 4, part(ii) 8, part (iii) 8

# G[2] =
#
# please justify point subtractions

In [ ]:
# total score
max_score = 36
final_score = sum(G)*(100/max_score)