<a href="https://colab.research.google.com/github/fahriyegrl/NJIT_Pytorch_Assignment/blob/main/Assignment_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Note to grader:** Each question consists of parts, e.g. Q1(i), Q1(ii), etc. Each part must be first graded  on a 0-4 scale, following the standard NJIT convention (A:4, B+: 3.5, B:3, C+: 2.5, C: 2, D:1, F:0). However, any given item may be worth 4 or 8 points; if an item is worth 8 points, you need to accordingly scale the 0-4 grade.


The total score must be re-scaled to 100. That should apply to all future assignments so that Canvas assigns the same weight on all assignments.



# Assignment 1



## Preparation Steps

In [2]:
# Import all necessary python packages
import numpy as np
import torch



## <font color = 'blue'> Question 1. Basic Operations with Tensors </font>

Your task for this question is to follow the NumPy  [**tutorial**](https://jalammar.github.io/visual-numpy/?fbclid=IwAR0tSntx5mj1aHteokRKrT4G6z77M3z0Quj40AQZ9mvKlhs2RTN3xXrc6Eo) and 'mirror' each of the operations presented in the tutorial with tensors in PyTorch.

You may find useful to consult this PyTorch introductory [tutorial](https://jhui.github.io/2018/02/09/PyTorch-Basic-operations/), and as always the full PyTorch [documentation](https://pytorch.org/docs/stable/torch.html) is the ultimate resource.

*(Please insert cells below for your answers )*

In [3]:
### Operation-1: Creating Arrays

x= torch.tensor([1,2,3])
ones= torch.ones(3)
zeros= torch.zeros(3)
randoms= torch.rand(3)
print(x)
print(ones)
print(zeros)
print(randoms)

tensor([1, 2, 3])
tensor([1., 1., 1.])
tensor([0., 0., 0.])
tensor([0.8758, 0.6382, 0.4498])


In [4]:
### Operation-2: Arithmetic(Addition/ Multiplication/Subtraction/DivisionScalar Multiplication)
result1 = x+ones
print(f"x+ones= {result1}")
result2 = x*ones
print(f"x*ones= {result2}")
result3 = x-ones
print(f"x-ones= {result3}")
result4 = x/ones
print(f"x/ones= {result4}")

x+ones= tensor([2., 3., 4.])
x*ones= tensor([1., 2., 3.])
x-ones= tensor([0., 1., 2.])
x/ones= tensor([1., 2., 3.])


In [5]:
### Operation-3: Indexing/Slicing
print(f"x= {x}")
sub = x[0]
print(f"x[0]= {sub}")
sub1 = x[1]
print(f"x[1]= {sub1}")
sub2 = x[0:2]
print(f"x[0:2]= {sub2}")
sub3 = x[1:]
print(f"x[1:]= {sub3}")


x= tensor([1, 2, 3])
x[0]= 1
x[1]= 2
x[0:2]= tensor([1, 2])
x[1:]= tensor([2, 3])


In [6]:
### Operation-4: Aggregation
min = x.min()
print(f"min= {min}")
max = x.max()
print(f"max= {max}")
sum = x.sum()
print(f"sum= {sum}")
mean = x.type(torch.float32).mean()
print(f"mean= {mean}")
std= x.type(torch.float32).std()
print(f"std= {std}")

min= 1
max= 3
sum= 6
mean= 2.0
std= 1.0


In [7]:
### Operation-5: Creating Matrices
matrix= torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
print(f"matrix= {matrix}")
ones_matrix = torch.ones((3, 2))
zeros_matrix = torch.zeros((3, 2))
random_matrix = torch.rand((3, 2))
print(f"ones_matrix= {ones_matrix}")
print(f"zeros_matrix= {zeros_matrix}")
print(f"random_matrix= {random_matrix}")

matrix= tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
ones_matrix= tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])
zeros_matrix= tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])
random_matrix= tensor([[0.8982, 0.8297],
        [0.2269, 0.9883],
        [0.2700, 0.6717]])


In [8]:
### Operation-6: Matrix Arithmetic
matrix1 = torch.tensor([[1, 2], [3, 4]])
matrix2 = torch.tensor([[5, 6], [7, 8]])
sum= matrix1+matrix2
print(f"matrix1+matrix2= {sum}")
sub= matrix1-matrix2
print(f"matrix1-matrix2= {sub}")
matrix3= torch.rand((3,2))
matrix4= torch.rand((1,2))
sum2= matrix3+matrix4
print(f"matrix3+matrix4= {sum2}")

matrix1+matrix2= tensor([[ 6,  8],
        [10, 12]])
matrix1-matrix2= tensor([[-4, -4],
        [-4, -4]])
matrix3+matrix4= tensor([[1.2611, 0.8697],
        [1.0020, 1.5832],
        [1.4994, 1.2515]])


In [9]:
### Operation-7: Dot Product
print(ones, randoms)
result= torch.dot(ones,randoms)
print(f"result= {result}")
result1 = torch.matmul(ones, randoms)
print(f"result1= {result1}")

tensor([1., 1., 1.]) tensor([0.8758, 0.6382, 0.4498])
result= 1.9638307094573975
result1= 1.9638307094573975


In [10]:
### Operation-8: Matrix Indexing
### Operation-8: Matrix Indexing
random_matrix = torch.rand((3, 2))
print(f"random_matrix: {random_matrix}")
print("***********************************")
print(f"random_matrix[0,1]: {random_matrix[0,1]}")
print("***********************************")
print(f"random_matrix[1:3]: {random_matrix[1:3]}")
print("***********************************")
print(f"random_matrix[0:2,0]: {random_matrix[0:2,0]}")

random_matrix: tensor([[0.1837, 0.7681],
        [0.0656, 0.6713],
        [0.9338, 0.2603]])
***********************************
random_matrix[0,1]: 0.7680814266204834
***********************************
random_matrix[1:3]: tensor([[0.0656, 0.6713],
        [0.9338, 0.2603]])
***********************************
random_matrix[0:2,0]: tensor([0.1837, 0.0656])


In [11]:
### Operation-9: Matrix Aggregation
max= random_matrix.max()
print(f"max= {max}")
min= random_matrix.min()
print(f"min= {min}")
sum= random_matrix.sum()
print(f"sum= {sum}")

print("***********************************")

max2= random_matrix.max(axis=0)
print(f"max2= {max2}")
max3= random_matrix.max(axis=1)
print(f"max3= {max3}")


max= 0.9337507486343384
min= 0.06563740968704224
sum= 2.882829189300537
***********************************
max2= torch.return_types.max(
values=tensor([0.9338, 0.7681]),
indices=tensor([2, 0]))
max3= torch.return_types.max(
values=tensor([0.7681, 0.6713, 0.9338]),
indices=tensor([1, 1, 0]))


In [12]:
### Operation-10: Transposing / Reshaping
transpose= random_matrix.T
print(f"transpose= {transpose}")
print("***********************************")
reshape= random_matrix.reshape(2,3)
print(f"reshape= {reshape}")

transpose= tensor([[0.1837, 0.0656, 0.9338],
        [0.7681, 0.6713, 0.2603]])
***********************************
reshape= tensor([[0.1837, 0.7681, 0.0656],
        [0.6713, 0.9338, 0.2603]])


In [13]:
### Operation-11: More Dimentions
ones_d = torch.ones((4, 3, 2))
print(f"ones_d= {ones_d}")
zeros_d = torch.zeros((4, 3, 2))
print(f"zeros_d= {zeros_d}")
random_d = torch.rand((4, 2, 2))
print(f"random_d= {random_d}")

ones_d= tensor([[[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]]])
zeros_d= tensor([[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]])
random_d= tensor([[[0.5938, 0.6890],
         [0.8058, 0.5522]],

        [[0.1911, 0.9794],
         [0.2367, 0.7451]],

        [[0.6236, 0.8300],
         [0.3199, 0.2151]],

        [[0.7801, 0.9225],
         [0.8800, 0.1616]]])


In [14]:
### Operation-12: Formulas
predictions = torch.tensor([3.6, 0.1, 4.1, 6.8])
labels = torch.tensor([3.0, -0.7, 3.0, 8.5])
n = predictions.size(0)
mean_square_error = (1 / n) * torch.sum(torch.square(predictions - labels))
print(f"mean_square_error= {mean_square_error}")

mean_square_error= 1.2749998569488525


In [15]:
### Data Representation: Tables and Spreadsheets

### In PyTorch, data loading from CSV files isn't done directly using PyTorch itself
### Once the data is read throth pandas or NumPy , it can be converted into a PyTorch tensor.

In [16]:
### Audio and Timeseries
### Python has libraries such as  torchaudio for audio data.
import torchaudio
audio_path = " "
#torchaudio.load(audio_path)

In [31]:
# For grader use only

G = [0]*2


# insert grade here  (from 0 to 8)
# G[1] =

# please justify point subtraction  s

##  <font color = 'blue'> Question 2. Quadratic Regression

In the lecture we discussed a simple regression problem, where points are coming from the line $y = 2x + 1$, plus some noise.  For this question you are asked to:

(i) Generate data points coming from a quadratic function: $ y = -x^2 + 3x +10 $, plus some noise. <br>
(ii) Modify the PyTorch model from the class in order for it to learn a quadratic function of the form $y = a x^2 + bx +c$. <br>
(iii) Train your model and report what values it computes. (Sanity check: These sould be close to -1, 3, 10)




In [30]:
###  Creating random x values
torch.manual_seed(42)
n_points = 100
x = torch.rand(n_points)
x[:5]

tensor([0.8823, 0.9150, 0.3829, 0.9593, 0.3904])

In [38]:
### Getting y based on y=−x2+3x+10
torch.manual_seed(42)
true_y = -x**2 + 3*x + 10
noise = torch.randn(n_points)
y = true_y + noise
y, true_y[:5]

(tensor([13.7953, 13.3951, 11.9027,  9.8521, 11.6973, 10.2071, 10.6608, 10.1464,
         11.1851, 12.0305, 11.5378, 10.0248, 11.1245, 10.8214, 10.9052, 11.8663,
         13.5146, 11.2327, 10.2313, 11.9282,  9.9781, 12.2076, 11.6034, 13.4840,
         11.5840, 12.0323, 11.5582, 11.8931, 11.1105, 10.0602, 11.6976, 11.0800,
         10.4883, 10.5383, 10.6756, 13.4898, 11.7187, 11.4702, 11.6621, 10.1352,
          9.9431, 11.9561, 10.7468, 11.3424, 10.4704, 12.8878, 10.5093, 10.9330,
         10.7795,  9.8895, 10.0931, 11.3521,  9.8479, 13.0936, 10.7033, 10.8853,
         10.1380, 11.2685, 11.8160, 11.0889, 11.2142, 12.2956, 10.3500, 12.2595,
         12.9781, 11.8872, 14.1255, 11.0926, 10.9113, 10.3673, 10.8926, 12.8335,
         11.8086, 10.7782, 10.0688, 10.7409, 11.0392, 10.9723,  9.3696, 11.1575,
         10.6778, 10.1134, 10.3695, 10.2196, 12.4056, 11.5819, 12.8072,  9.8720,
         10.0029, 12.1060, 11.6380, 10.6212, 12.0222, 13.0874, 10.3920, 10.3413,
         10.9696, 11.0074, 1

In [41]:
torch.manual_seed(42)
idx = torch.arange(100)
shuffled_idx = idx[torch.randperm(100)]

print(shuffled_idx)

tensor([42, 96, 62, 98, 46, 95, 60, 24, 78, 16, 68, 70, 11, 13, 97, 52, 99, 19,
        71, 10, 89, 86, 18, 40,  5, 38,  9, 82, 83, 43, 32, 94, 67, 93, 75, 59,
        79,  1, 50, 73, 66, 45, 63, 58, 22,  3, 87,  4, 61, 51, 12, 74, 21, 20,
         6, 35, 44, 48, 37, 33, 15, 88, 31, 69, 27, 81, 85, 56,  7, 65, 47, 41,
        29, 80, 57, 84, 36, 17, 34, 72,  2, 91,  8, 53, 30, 90, 26, 23, 54, 76,
        14, 55,  0, 64, 77, 39, 25, 92, 49, 28])


In [44]:
train_idx = idx[:80]
val_idx = idx[80:]

# Generates train and validation sets
x_train, y_train = x[train_idx], y[train_idx]
x_val, y_val = x[val_idx], y[val_idx]

In [45]:
x_train.shape, y_train.shape, x_val.shape, y_val.shape

(torch.Size([80]), torch.Size([80]), torch.Size([20]), torch.Size([20]))

In [35]:
# for grader use only

# insert grade here
# part (i): 4, part(ii) 8, part (iii) 8

# G[2] =
#
# please justify point subtractions

In [36]:
# total score
max_score = 36
final_score = sum(G)*(100/max_score)

TypeError: 'Tensor' object is not callable